name: "Build"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Run Tests
        run: flutter test
        
      - name: Analyze Code
        run: flutter analyze

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: test  # Only build if tests pass
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest 

      - name: Generate Version from Tags
        id: generate_version
        run: |
          # Get the latest tag, if no tags exist, start with 1.0.0
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          
          # Remove 'v' prefix if present
          version_number=${latest_tag#v}
          
          # Get commit count since the latest tag
          commit_count=$(git rev-list --count ${latest_tag}..HEAD 2>/dev/null || echo "0")
          
          # If there are commits since the tag, increment patch version
          if [ "$commit_count" -gt 0 ]; then
            IFS='.' read -r major minor patch <<< "$version_number"
            patch=$((patch + 1))
            new_version="$major.$minor.$patch"
          else
            new_version="$version_number"
          fi
          
          echo "Generated version: $new_version"
          echo "VERSION=$new_version" >> $GITHUB_ENV
          echo "version=$new_version" >> $GITHUB_OUTPUT

      - name: Update pubspec.yaml version
        run: |
          # Update the version in pubspec.yaml
          sed -i "s/^version: .*/version: ${{ steps.generate_version.outputs.version }}/" pubspec.yaml
          echo "Updated pubspec.yaml version to ${{ steps.generate_version.outputs.version }}"

      - name: Install Dependencies
        run: flutter pub get

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Firebase
        run: npm install -g firebase-tools

      - name: Install FlutterFire CLI
        run: |
          dart pub global activate flutterfire_cli

      - name: Setup Google Cloud credentials
        run: |
          # Create the credentials file from the secret
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > $HOME/gcloud-service-key.json
          # Set the environment variable to point to the credentials file
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service-key.json" >> $GITHUB_ENV

      - name: Generate firebase config files
        run: |
          # Configure Firebase using FlutterFire CLI
          flutterfire configure \
            --project=${{ secrets.FIREBASE_PROJECT_ID }} \
            --yes \
            --platforms=android,web
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-service-key.json

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ steps.generate_version.outputs.version }}
          path: |
            build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30

      - name: Upload Version Info
        uses: actions/upload-artifact@v4
        with:
          name: version-info-${{ steps.generate_version.outputs.version }}
          path: |
            pubspec.yaml
          retention-days: 30

    outputs:
      version: ${{ steps.generate_version.outputs.version }}
      artifact-name: build-artifacts-${{ steps.generate_version.outputs.version }}
